apiVersion: apps/v1
kind: Deployment
metadata:
  name: znn
  labels:
    app: znn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: znn
      tier: frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: znn
        tier: frontend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9180"
    spec:
      volumes:
      - name: shared-files
        emptyDir: {}
      containers:
      - name: znn
        image: cmendes/znn:high
        imagePullPolicy: Always
        env:
        #- name: FIDELITY_FILE
        #  value: "/var/www/html/fidelity.txt"
        - name: DB_HOST
          value: "znn-db"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "znn_data"
        - name: DB_USER
          value: "znn"
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        readinessProbe:
          httpGet:
            path: /readiness.php
            port: 80
          initialDelaySeconds: 2
          periodSeconds: 2
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /liveness.php
            port: 80
          initialDelaySeconds: 1
          periodSeconds: 1
          failureThreshold: 5
        ports:
        - containerPort: 80
          name: znn
        - containerPort: 9180
          name: caddy-exporter
        volumeMounts:
        - name: shared-files
          mountPath: /var/www/html