kind: PersistentVolume
apiVersion: v1
metadata:
  name: znn-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/carlosmendes/unifor/znn/src"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: znn-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi