apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: grafana-prom-datasource
  namespace: monitoring
data:
    prometheus-datasource.yaml: |
      apiVersion: 1
      datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        editable: false