apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: probes
data:
  probes.yaml: |
    vars:
      _probes.commonPath: "/etc/kubow/targets/kube-znn"
      
    probes:

      CustomMetricsProbe:
        alias: kube-znn.latency.probe
        location: 127.0.0.1
        type: java
        javaInfo:
          class: org.sa.rainbow.translator.probes.CustomMetricProbe
          period: 5000
          args.length: 5
          args.0: default
          args.1: kube-znn
          args.2: selector?app=kube-znn
          args.3: caddy_http_request_duration_seconds_success_99p
          args.4: latency

      DeploymentPropertiesProbe:
        alias: deployments.default.kube-znn.probe
        location: 127.0.0.1
        type: java
        javaInfo:
          class: org.sa.rainbow.translator.probes.DeploymentInfoProbe
          period: 5000
          args.length: 2
          args.0: "default"
          args.1: "kube-znn"
