apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: probes
data:
  probes.yaml: |
    probes:
      DeploymentPropertiesProbe:
        alias: deployments.default.znn.probe
        location: 127.0.0.1
        type: java
        javaInfo:
          class: org.sa.rainbow.translator.probes.DeploymentInfoProbe
          period: 2000
          args.length: 3
          args.0: "default"
          args.1: "znn"
          args.2: "app=znn"

      LatencyPrometheusProbe:
        alias: default-znn-latency
        location: 127.0.0.1
        type: java
        javaInfo:
          class: org.sa.rainbow.translator.probes.PrometheusProbe
          period: 2000
          args.length: 4
          args.0: "default"
          args.1: "znn"
          args.2: "latency"
          args.3: "histogram_quantile(0.95, sum(irate(caddy_http_request_duration_seconds_bucket{namespace!=\"\",pod=~\"znn.*\"}[1m])) by (le))*1000"
