apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: tactics
data:
  tactics.s: |
    module kuberainbow.strategies;
    import model "KubeZnnSystem:Acme" { KubeZnnSystem as M, Kubernetes as K };
    import op "org.sa.rainbow.stitch.lib.*";

    define boolean lowMode = org.sa.rainbow.stitch.Operators.containerImage(M.kubeZnnD, "znn", "cmendes/znn:low");
    define boolean highMode = org.sa.rainbow.stitch.Operators.containerImage(M.kubeZnnD, "znn", "cmendes/znn:high");
    define boolean cHiRespTime = M.kubeZnnS.latency > M.MAX_RESPTIME;
    define boolean canAddPods = M.kubeZnnD.maxReplicas > M.kubeZnnD.desiredReplicas;
    define boolean canRemovePods = M.kubeZnnD.minReplicas < M.kubeZnnD.desiredReplicas;

    tactic addReplicas(int count) {
      condition {
        cHiRespTime && canAddPods;
      }
      action {
        M.scaleUp(M.kubeZnnD, M.kubeZnnD.desiredReplicas + count);
      }
      effect {
        M.kubeZnnD.maxReplicas >= M.kubeZnnD.desiredReplicas;
      }
    }

    tactic removeReplicas(int count) {
      condition {
        !cHiRespTime && canRemovePods;
      }
      action {
        M.scaleDown(M.kubeZnnD, M.kubeZnnD.desiredReplicas - count);
      }
      effect {
        M.kubeZnnD.minReplicas <= M.kubeZnnD.desiredReplicas;
      }
    }

    tactic lowerFidelity() {
      condition {
        (lowMode || highMode) && cHiRespTime;
      }
      action {
        if (highMode) {
          M.rollOut(M.kubeZnnD, "znn", "cmendes/znn:low");
        }

        if (lowMode) {
          M.rollOut(M.kubeZnnD, "znn", "cmendes/znn:text");
        }
      }
      effect {
        !highMode;
      }
    }